# Generated by Django 3.0.4 on 2020-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200308_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
