# Generated by Django 3.0.4 on 2020-03-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_activity_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_pubdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
