# Generated by Django 3.0.4 on 2020-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200308_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_addr',
            field=models.CharField(default='', max_length=50),
        ),
    ]
