# Generated by Django 3.0.4 on 2020-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_activity_activity_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_loc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
